Admin.create(email: "test@test.com", password: "test123")

Course.create(name: "Psychology", total_hours: 40)
Course.create(name: "Sociology", total_hours: 50)
Course.create(name: "Anthropology", total_hours: 60)
Course.create(name: "TEST", total_hours: 1)
Course.create(name: "TEST2", total_hours: 2)

Cohort.create(name: "PSY101", start_date: '2018-05-03', end_date: '2018-06-03', instructor_id: 1, course_id: 1)
Cohort.create(name: "PSY102", start_date: '2018-05-03', end_date: '2018-06-03', instructor_id: 1, course_id: 1)
Cohort.create(name: "SOC101", start_date: '2018-06-03', end_date: '2018-07-03', instructor_id: 2, course_id: 2)
Cohort.create(name: "SOC102", start_date: '2018-06-03', end_date: '2018-07-03', instructor_id: 2, course_id: 2)
Cohort.create(name: "ANT101", start_date: '2018-07-03', end_date: '2018-05-03', instructor_id: 3, course_id: 2)
Cohort.create(name: "ANT102", start_date: '2018-07-03', end_date: '2018-05-03', instructor_id: 3, course_id: 1)
Cohort.create(name: "TEST101", start_date: '2018-01-01', end_date: '2018-02-02', instructor_id: 1, course_id: 1)
Cohort.create(name: "TEST202", start_date: '2018-03-03', end_date: '2018-03-04', instructor_id: 2, course_id: 2)

Instructor.create(first_name: "T'Challa", last_name: "Wakanda", age: "30", salary: "50000", education: "College", cohort_id: 1)
Instructor.create(first_name: "Bruce", last_name: "Wayne", age: "40", salary: "60000", education: "Masters", cohort_id: 2)
Instructor.create(first_name: "Tony", last_name: "Stark", age: "50", salary: "70000", education: "PhD", cohort_id: 3)
Instructor.create(first_name: "TESTFIRST", last_name: "TESTLAST", age: "20", salary: "10000", education: "Masters", cohort_id: 3)
Instructor.create(first_name: "TESTFIRST2", last_name: "TESTLAST2", age: "30", salary: "20000", education: "PhD", cohort_id: 5)

Student.create(first_name: "Snow", last_name: "White", age: "25", education: "PhD", cohort_id: 1)
Student.create(first_name: "Ariel", last_name: "Mermaid", age: "26", education: "College", cohort_id: 1)
Student.create(first_name: "King", last_name: "James", age: "27", education: "Masters", cohort_id: 1)
Student.create(first_name: "Ursula", last_name: "Queen", age: "28", education: "Masters", cohort_id: 1)
Student.create(first_name: "Cinder", last_name: "Ella", age: "29", education: "HS", cohort_id: 1)
Student.create(first_name: "Tiana", last_name: "Princess", age: "30", education: "HS", cohort_id: 1)
Student.create(first_name: "Belle", last_name: "Beast", age: "24", education: "College", cohort_id: 1)
Student.create(first_name: "Hakuna", last_name: "Matata", age: "23", education: "College", cohort_id: 1)
Student.create(first_name: "Simba", last_name: "Lion", age: "31", education: "College", cohort_id: 1)
Student.create(first_name: "Mufasa", last_name: "Rafiki", age: "32", education: "Masters", cohort_id: 1)
Student.create(first_name: "King", last_name: "Cole", age: "33", education: "Masters", cohort_id: 1)
Student.create(first_name: "Humpty", last_name: "Dumpty", age: "34", education: "HS", cohort_id: 1)
Student.create(first_name: "TEST2", last_name: "TEST2", age: "22", education: "HS", cohort_id: 2)
Student.create(first_name: "TEST3", last_name: "TEST3", age: "52", education: "Masters", cohort_id: 2)
